apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: 3t
    tier: mysql
  namespace: test-lc-kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 3t
      tier: mysql
  template:
    metadata:
      labels:
        app: 3t
        tier: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "root"
          - name: MYSQL_DATABASE
            value: "test_db"
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
          - name: mysql
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: mysql