apiVersion: v1
kind: ConfigMap
metadata:
  name: varnish-vcl
  namespace: test-lc-kustomize
  labels:
    app: 3t
    tier: varnish
data:
  default.vcl: |
    vcl 4.0;

    backend default {
        .host = "django";
        .port = "8000";
    }

    # For testing purposes
    sub vcl_backend_response {
        set beresp.ttl = 1s;
    }