apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "varnish.fullname" . }}
  labels:
    {{- include "varnish.labels" . | nindent 4 }}
data:
  default.vcl: |
    vcl 4.0;

    backend default {
        .host = "{{ .Values.backend.host }}";
        .port = "{{ .Values.backend.port }}";
    }

    # For testing purposes
    sub vcl_backend_response {
        set beresp.ttl = 1s;
    }