---
apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app: 3t
    tier: django
  namespace: test-lc-kustomize
spec:
  ports:
    - port: 8000
  selector:
    app: 3t
    tier: django
  clusterIP: None