---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: 3t
    tier: django
    app.kubernetes.io/name: django
    helm.sh/chart: django-0.1.0
    app.kubernetes.io/instance: django
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 1.16.0
  namespace: test-lc-manifest
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: "django"
    meta.helm.sh/release-namespace: "test-lc-manifest"
spec:
  selector:
    matchLabels:
      app: 3t
      tier: django
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: 3t
        tier: django
    spec:
      containers:
      - image: lkamz/django-webapp:1.2
        command: ['docker-entrypoint.sh']
        name: django
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: DJANGO_ALLOWED_HOSTS
          value: "*"
        - name: DATABASE_HOST
          value: "mysql"
        - name: DATABASE_NAME
          value: "django"
        - name: DATABASE_USERNAME
          value: "django"
        - name: DATABASE_ENGINE
          value: "mysql"
        - name: DATABASE_PORT
          value: "3306"
        - name: CONFIGURE_MYSQL_CONNECTION
          value: "true"
        - name: DJANGO_SECRET_KEY
          value: "root"
        - name: MYSQL_DB_PASSWORD
          value: "root"
        - name: DATABASE_DJANGO_PASSWORD
          value: "root"
        ports:
        - containerPort: 8000
          name: django
