apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: 3t
    tier: mysql
  namespace: test-lc-manifest
spec:
  type: NodePort
  ports:
    - port: 3306
      protocol: TCP
      name: mysql
  selector:
    app: 3t
    tier: mysql