# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql
#   labels:
#     app: 3t
#     tier: mysql
#   namespace: test-lc-manifest
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi